version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sapphire-prediksi
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sapphire.rule=Host(`sapphirespk.cnzr.biz.id `)"
      - "traefik.http.routers.sapphire.entrypoints=websecure"
      - "traefik.http.routers.sapphire.tls.certresolver=letsencrypt"
      - "traefik.http.services.sapphire.loadbalancer.server.port=5000"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
